// Gate for the whole app. Everything is private unless it appears below —
// prospects and search engines see the marketing site and their own preview,
// the operator sees the rest after logging in.
//
// Next 16 renamed the `middleware` convention to `proxy`. It runs on the Node.js
// runtime by default, so node:crypto works here directly; setting
// `export const runtime` in this file would throw.
import { NextResponse, type NextRequest } from "next/server";
import { SESSION_COOKIE, verifySession } from "@/lib/auth/session";

/** Public in full, matched exactly. */
const PUBLIC_PATHS = new Set([
  "/",
  "/examples",
  "/login",
  "/favicon.ico",
  // The generated OG card. Extensionless, so it misses STATIC_FILE below — and
  // a link unfurler carries no cookie, so gating it means no preview anywhere.
  "/opengraph-image",
  "/robots.txt",
  "/sitemap.xml",
  // App icons, generated by Next from src/app/ and served at these exact paths.
  "/icon.svg",
  "/apple-icon.png",
  // Next's starter assets in public/. Unreferenced today, listed so that removing
  // the blanket extension rule below cannot 302 an image that something still uses.
  "/file.svg",
  "/next.svg",
  "/globe.svg",
  "/vercel.svg",
  "/window.svg",
  // Stripe signs its own requests and cannot carry our cookie. The route verifies
  // the signature itself, which is the real authentication here.
  "/api/stripe/webhook",
]);

/** Public including everything beneath them. */
const PUBLIC_PREFIXES = [
  "/p/", // a prospect's shareable preview — the whole point of outreach
  "/api/p/", // its "I'm interested" button
  "/api/site/", // contact forms embedded in generated sites
  "/pay/", // Stripe Checkout return pages
  "/previews/", // preview screenshots under public/
  "/brand/", // logo files under public/, used by the marketing pages
  "/api/auth/", // login and logout themselves
  "/_next/", // build assets
];

/**
 * Whether this path is served to anyone, logged in or not.
 *
 * There was a rule here that made ANY path ending in an image/font/text
 * extension public, so that assets in public/ resolved for a logged-out visitor.
 * It has been replaced by the explicit /brand/ prefix and the icon paths above,
 * because it decided the answer to "is this private?" from a trailing string a
 * caller controls rather than from the route. Nothing reachable today slipped
 * through it — every dynamic segment is an exact-match id lookup that 404s — but
 * it would have silently opened the first future route whose path happened to
 * end that way, in the one file whose whole job is to be airtight and readable.
 */
function isPublic(pathname: string): boolean {
  if (PUBLIC_PATHS.has(pathname)) return true;
  return PUBLIC_PREFIXES.some((prefix) => pathname.startsWith(prefix));
}

export function proxy(req: NextRequest) {
  const { pathname, search } = req.nextUrl;

  if (isPublic(pathname)) return NextResponse.next();

  // Fail closed. A missing secret means sessions cannot be verified, so serving
  // the console would mean serving it to everyone — better a loud 503.
  if (!process.env.AUTH_SECRET) {
    return new NextResponse("Auth is not configured on this server.", {
      status: 503,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  }

  if (verifySession(req.cookies.get(SESSION_COOKIE)?.value)) {
    return NextResponse.next();
  }

  // API callers get JSON. The console's fetch() calls would otherwise receive an
  // HTML login page and die inside res.json() with a parse error that says
  // nothing about the real problem.
  if (pathname.startsWith("/api/")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const login = new URL("/login", req.url);
  login.searchParams.set("next", pathname + search);
  return NextResponse.redirect(login);
}

export const config = {
  // Only build assets are skipped here; everything else is decided in isPublic()
  // above, so there is one allowlist to read rather than two that must agree.
  matcher: ["/((?!_next/static|_next/image).*)"],
};
